function [underrun,BER,overflow,output] = runSDRQPSK_text(prmQPSKTransmitter,prmQPSKReceiver,previewData,printData)
%#codegen

%   Copyright 2012-2023 The MathWorks, Inc.

persistent qpskTx radioTx
if isempty(qpskTx)
    % Initialize the components
    % Create and configure the transmitter System object
    qpskTx = QPSKTransmitter(...
        'UpsamplingFactor',             prmQPSKTransmitter.Interpolation, ...
        'RolloffFactor',                prmQPSKTransmitter.RolloffFactor, ...
        'RaisedCosineFilterSpan',       prmQPSKTransmitter.RaisedCosineFilterSpan, ...
        'MessageBits',                  prmQPSKTransmitter.MessageBits, ...
        'MessageLength',                prmQPSKTransmitter.MessageLength, ...
        'NumberOfMessage',              prmQPSKTransmitter.NumberOfMessage, ...
        'ScramblerBase',                prmQPSKTransmitter.ScramblerBase, ...
        'ScramblerPolynomial',          prmQPSKTransmitter.ScramblerPolynomial, ...
        'ScramblerInitialConditions',   prmQPSKTransmitter.ScramblerInitialConditions);

    % Create and configure the SDRu System object. Set the SerialNum for B2xx
    % radios and IPAddress for X3xx, N2xx, and USRP2 radios. MasterClockRate
    % is not configurable for N2xx and USRP2 radios.
    switch prmQPSKTransmitter.Platform
        %%% PLUTO Radio %%%
        case {'ADALM-PLUTO'}
               % Create and configure the Pluto System object.
               radioTx = sdrtx('Pluto');
               radioTx.RadioID               = prmQPSKTransmitter.Address;
               radioTx.CenterFrequency       = prmQPSKTransmitter.PlutoCenterFrequency;
               radioTx.BasebandSampleRate    = prmQPSKTransmitter.PlutoFrontEndSampleRate;
               radioTx.SamplesPerFrame       = prmQPSKTransmitter.PlutoFrameLength;
               radioTx.Gain                  = prmQPSKTransmitter.PlutoGain;
        %%% USRP Radios %%%
        case {'B200','B210'}
            radioTx = comm.SDRuTransmitter(...
                'Platform',             prmQPSKTransmitter.Platform, ...
                'SerialNum',            prmQPSKTransmitter.Address, ...
                'MasterClockRate',      prmQPSKTransmitter.MasterClockRate, ...
                'CenterFrequency',      prmQPSKTransmitter.USRPCenterFrequency, ...
                'Gain',                 prmQPSKTransmitter.USRPGain, ...
                'InterpolationFactor',  prmQPSKTransmitter.USRPInterpolationFactor);
        case {'X300','X310'}
            radioTx = comm.SDRuTransmitter(...
                'Platform',             prmQPSKTransmitter.Platform, ...
                'IPAddress',            prmQPSKTransmitter.Address, ...
                'MasterClockRate',      prmQPSKTransmitter.MasterClockRate, ...
                'CenterFrequency',      prmQPSKTransmitter.USRPCenterFrequency, ...
                'Gain',                 prmQPSKTransmitter.USRPGain, ...
                'InterpolationFactor',  prmQPSKTransmitter.USRPInterpolationFactor);
        case {'N200/N210/USRP2'}
            radioTx = comm.SDRuTransmitter(...
                'Platform',             prmQPSKTransmitter.Platform, ...
                'IPAddress',            prmQPSKTransmitter.Address, ...
                'CenterFrequency',      prmQPSKTransmitter.USRPCenterFrequency, ...
                'Gain',                 prmQPSKTransmitter.USRPGain, ...
                'InterpolationFactor',  prmQPSKTransmitter.USRPInterpolationFactor);
        case {'N300','N310'}
            radioTx = comm.SDRuTransmitter(...
                'Platform',             prmQPSKTransmitter.Platform, ...
                'IPAddress',            prmQPSKTransmitter.Address, ...
                'MasterClockRate',      prmQPSKTransmitter.MasterClockRate, ...
                'CenterFrequency',      prmQPSKTransmitter.USRPCenterFrequency, ...
                'Gain',                 prmQPSKTransmitter.USRPGain, ...
                'InterpolationFactor',  prmQPSKTransmitter.USRPInterpolationFactor);
        case {'N320/N321'}
            radioTx = comm.SDRuTransmitter(...
                'Platform',             prmQPSKTransmitter.Platform, ...
                'IPAddress',            prmQPSKTransmitter.Address, ...
                'MasterClockRate',      prmQPSKTransmitter.MasterClockRate, ...
                'CenterFrequency',      prmQPSKTransmitter.USRPCenterFrequency, ...
                'Gain',                 prmQPSKTransmitter.USRPGain, ...
                'InterpolationFactor',  prmQPSKTransmitter.USRPInterpolationFactor);
    end
end

cleanupTx = onCleanup(@()release(qpskTx));
cleanupRadio = onCleanup(@()release(radioTx));

persistent qpskRx radioRx
if isempty(qpskRx)
    qpskRx = QPSKReceiver(...
        'ModulationOrder',                      prmQPSKReceiver.ModulationOrder, ...
        'SampleRate',                           prmQPSKReceiver.Fs, ...
        'DecimationFactor',                     prmQPSKReceiver.Decimation, ...
        'FrameSize',                            prmQPSKReceiver.FrameSize, ...
        'HeaderLength',                         prmQPSKReceiver.HeaderLength, ...
        'NumberOfMessage',                      prmQPSKReceiver.NumberOfMessage, ...
        'PayloadLength',                        prmQPSKReceiver.PayloadLength, ...
        'DesiredPower',                         prmQPSKReceiver.DesiredPower, ...
        'AveragingLength',                      prmQPSKReceiver.AveragingLength, ...
        'MaxPowerGain',                         prmQPSKReceiver.MaxPowerGain, ...
        'RolloffFactor',                        prmQPSKReceiver.RolloffFactor, ...
        'RaisedCosineFilterSpan',               prmQPSKReceiver.RaisedCosineFilterSpan, ...
        'InputSamplesPerSymbol',                prmQPSKReceiver.Interpolation, ...
        'MaximumFrequencyOffset',               prmQPSKReceiver.MaximumFrequencyOffset, ...
        'PostFilterOversampling',               prmQPSKReceiver.Interpolation/prmQPSKReceiver.Decimation, ...
        'PhaseRecoveryLoopBandwidth',           prmQPSKReceiver.PhaseRecoveryLoopBandwidth, ...
        'PhaseRecoveryDampingFactor',           prmQPSKReceiver.PhaseRecoveryDampingFactor, ...
        'TimingRecoveryDampingFactor',          prmQPSKReceiver.TimingRecoveryDampingFactor, ...
        'TimingRecoveryLoopBandwidth',          prmQPSKReceiver.TimingRecoveryLoopBandwidth, ...
        'TimingErrorDetectorGain',              prmQPSKReceiver.TimingErrorDetectorGain, ...
        'PreambleDetectionThreshold',           prmQPSKReceiver.PreambleDetectionThreshold, ...
        'DescramblerBase',                      prmQPSKReceiver.ScramblerBase, ...
        'DescramblerPolynomial',                prmQPSKReceiver.ScramblerPolynomial, ...
        'DescramblerInitialConditions',         prmQPSKReceiver.ScramblerInitialConditions,...
        'BerMask',                              prmQPSKReceiver.BerMask, ...
        'CFCAlgorithm',                         prmQPSKReceiver.CFCAlgorithm, ...
        'Preview',                              previewData, ...
        'PrintOption',                          printData);

    % Create and configure the SDRu System object. Set the SerialNum for B2xx
    % radios and IPAddress for X3xx, N2xx, N3xx, and USRP2 radios. MasterClockRate
    % is not configurable for N2xx and USRP2 radios.
    switch prmQPSKReceiver.Platform
        %%% PLUTO Radio %%%
        case {'ADALM-PLUTO'}
            radioRx = sdrrx('Pluto', OutputDataType = 'double');
            radioRx.RadioID               = prmQPSKReceiver.Address;
            radioRx.CenterFrequency       = prmQPSKReceiver.PlutoCenterFrequency;
            radioRx.BasebandSampleRate    = prmQPSKReceiver.PlutoFrontEndSampleRate;
            radioRx.SamplesPerFrame       = prmQPSKReceiver.PlutoFrameLength;
            radioRx.GainSource            = 'Manual';
            radioRx.Gain                  = prmQPSKReceiver.PlutoGain;
        %%% USRP Radios %%%
        case {'B200','B210'}
            radioRx = comm.SDRuReceiver(...
                'Platform',             prmQPSKReceiver.Platform, ...
                'SerialNum',            prmQPSKReceiver.Address, ...
                'MasterClockRate',      prmQPSKReceiver.MasterClockRate, ...
                'CenterFrequency',      prmQPSKReceiver.USRPCenterFrequency, ...
                'Gain',                 prmQPSKReceiver.USRPGain, ...
                'DecimationFactor',     prmQPSKReceiver.USRPDecimationFactor, ...
                'SamplesPerFrame',      prmQPSKReceiver.USRPFrameLength, ...
                'OutputDataType',       'double');
        case {'X300','X310'}
            radioRx = comm.SDRuReceiver(...
                'Platform',             prmQPSKReceiver.Platform, ...
                'IPAddress',            prmQPSKReceiver.Address, ...
                'MasterClockRate',      prmQPSKReceiver.MasterClockRate, ...
                'CenterFrequency',      prmQPSKReceiver.USRPCenterFrequency, ...
                'Gain',                 prmQPSKReceiver.USRPGain, ...
                'DecimationFactor',     prmQPSKReceiver.USRPDecimationFactor, ...
                'SamplesPerFrame',      prmQPSKReceiver.USRPFrameLength, ...
                'OutputDataType',       'double');
        case {'N200/N210/USRP2'}
            radioRx = comm.SDRuReceiver(...
                'Platform',             prmQPSKReceiver.Platform, ...
                'IPAddress',            prmQPSKReceiver.Address, ...
                'CenterFrequency',      prmQPSKReceiver.USRPCenterFrequency, ...
                'Gain',                 prmQPSKReceiver.USRPGain, ...
                'DecimationFactor',     prmQPSKReceiver.USRPDecimationFactor, ...
                'SamplesPerFrame',      prmQPSKReceiver.USRPFrameLength, ...
                'OutputDataType',       'double');
        case {'N300','N310'}
            radioRx = comm.SDRuReceiver(...
                'Platform',             prmQPSKReceiver.Platform, ...
                'IPAddress',            prmQPSKReceiver.Address, ...
                'MasterClockRate',      prmQPSKReceiver.MasterClockRate, ...
                'CenterFrequency',      prmQPSKReceiver.USRPCenterFrequency, ...
                'Gain',                 prmQPSKReceiver.USRPGain, ...
                'DecimationFactor',     prmQPSKReceiver.USRPDecimationFactor, ...
                'SamplesPerFrame',      prmQPSKReceiver.USRPFrameLength, ...
                'OutputDataType',       'double');
        case {'N320/N321'}
            radioRx = comm.SDRuReceiver(...
                'Platform',             prmQPSKReceiver.Platform, ...
                'IPAddress',            prmQPSKReceiver.Address, ...
                'MasterClockRate',      prmQPSKReceiver.MasterClockRate, ...
                'CenterFrequency',      prmQPSKReceiver.USRPCenterFrequency, ...
                'Gain',                 prmQPSKReceiver.USRPGain, ...
                'DecimationFactor',     prmQPSKReceiver.USRPDecimationFactor, ...
                'SamplesPerFrame',      prmQPSKReceiver.USRPFrameLength, ...
                'OutputDataType',       'double');

    end
end

cleanupRx = onCleanup(@()release(qpskRx));
cleanupRadio = onCleanup(@()release(radioRx));

currentTime = 0;
underrun = 0;
overflow = 0;
output = [];
%Transmission Process
while currentTime < prmQPSKReceiver.StopTime
    % Bit generation, modulation and transmission filtering
    data = qpskTx();

    % Data transmission
    tunderrun = radioTx(data);
    
    [rcvdSignal, ~, toverflow] = radioRx();

    if ~toverflow % Avoid overflow frames for continuous-mode receiver synchronization
       [~, ~, ~, BER, toutput] = qpskRx(rcvdSignal); % Receiver
       if previewData
          output = [output; toutput]; %#ok<AGROW>
       end
    else
       overflow = toverflow + overflow;
    end
    underrun = underrun + tunderrun;
    % Update simulation time
    currentTime=currentTime + prmQPSKReceiver.SDRFrameTime;
end

if previewData
    output = int8(bi2de(reshape(output, 7, [])', 'left-msb'));
    output = sprintf('%s', char(output));
    fprintf('%s', output(1:96));
    fprintf('...\n...\n');
    disp('<a href="matlab: fprintf(''%s'', output);">Show all messages</a>');
end